Module1 task3
htmlacademy-nodejs/1534899-typoteka-3 pull request #4
Opened 2021-08-29 19:29 UTC by StormWindRunner

2021-08-30 08:14 UTC, what1s1ove requested changes

2021-08-30 08:14 UTC, what1s1ove commented on src/service/cli/index.js
> +const version = require("./version");
по проекту гуляют разные кавычки
запускае линтер, перед коммитом/пушом

2021-08-30 08:16 UTC, StormWindRunner commented on src/service/cli/index.js
> +const version = require("./version");
ок

2021-08-31 13:12 UTC, what1s1ove approved these changes

2021-08-31 13:12 UTC, what1s1ove commented on src/service/constants.js
> +const EXIT_CODES = {
```suggestion
const ExitCode = {
```
это енам

2021-08-31 13:12 UTC, what1s1ove commented on src/service/constants.js
> +const DATE = new Date().toLocaleDateString(undefined, {
это не константа. Константа не должна высчитываться

2021-08-31 13:12 UTC, merged